version: "3.8"

services:
  student-db:
    image: postgres:14.1-alpine
    restart: unless-stopped
    volumes:
      - student-dbdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${POSTGRES_DATABASE_PASSWORD}

  student-backend:
    image: officialdarnyc/sesc-student-backend:v3
    restart: on-failure
    deploy:
      resources:
        limits:
          cpus: "0.5" # Limit the container to use 50% of a single CPU core
          memory: "50M" # Limit the container to use 50 megabytes of memory
    environment:
      - POSTGRES_DATABASE_HOST=student-db
      - POSTGRES_DATABASE_USERNAME=postgres
      - POSTGRES_DATABASE_PASSWORD=${POSTGRES_DATABASE_PASSWORD}
      - POSTGRES_DATABASE_NAME=postgres
      - POSTGRES_DATABASE_PORT=5432
    ports:
      - "8080:8080"
    depends_on:
      - student-db

  student-frontend:
    image: officialdarnyc/sesc-student-frontend:v2
    ports:
      - "3002:3000"

volumes:
  student-dbdata: